/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const VideoChannel = IDL.Record({
  'categoryId' : IDL.Text,
  'lastPlayed' : IDL.Opt(Time),
  'channelId' : IDL.Text,
  'views' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'safe' : IDL.Bool,
  'lastUpdated' : IDL.Opt(Time),
  'description' : IDL.Text,
  'isFavorite' : IDL.Bool,
  'playlistUrl' : IDL.Text,
  'approved' : IDL.Bool,
  'totalVideos' : IDL.Nat,
  'iconUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TextBubble = IDL.Record({
  'content' : IDL.Text,
  'character' : IDL.Text,
  'style' : IDL.Text,
  'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
});
export const AvatarConfig = IDL.Record({
  'body' : IDL.Text,
  'hair' : IDL.Text,
  'head' : IDL.Text,
  'headwear' : IDL.Text,
  'shoes' : IDL.Text,
  'pants' : IDL.Text,
});
export const Character = IDL.Record({
  'name' : IDL.Text,
  'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
  'avatarConfig' : AvatarConfig,
});
export const Prop = IDL.Record({
  'name' : IDL.Text,
  'type' : IDL.Text,
  'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
});
export const Scene = IDL.Record({
  'background' : IDL.Text,
  'textBubbles' : IDL.Vec(TextBubble),
  'characters' : IDL.Vec(Character),
  'animations' : IDL.Vec(IDL.Text),
  'props' : IDL.Vec(Prop),
});
export const StoryProject = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'scenes' : IDL.Vec(Scene),
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'approved' : IDL.Bool,
});
export const AccessibilitySettings = IDL.Record({
  'highContrastMode' : IDL.Bool,
  'largeText' : IDL.Bool,
  'readAloudEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'mascotPreference' : IDL.Text,
  'theme' : IDL.Text,
  'approvedContacts' : IDL.Vec(IDL.Principal),
  'parentPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'screenTimeLimit' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'contentFilterLevel' : IDL.Text,
  'avatarConfig' : IDL.Opt(AvatarConfig),
  'accessibilitySettings' : AccessibilitySettings,
});
export const VirtualPetHub = IDL.Record({
  'growthStage' : IDL.Nat,
  'accessories' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'warnedAboutExtremeChanges' : IDL.Bool,
  'happinessLevel' : IDL.Nat,
  'petName' : IDL.Text,
  'trophies' : IDL.Nat,
  'homeStyle' : IDL.Text,
  'decorations' : IDL.Vec(IDL.Text),
});
export const ActivityType = IDL.Variant({
  'user_created' : IDL.Null,
  'game_played' : IDL.Record({ 'gameId' : IDL.Text, 'gameName' : IDL.Text }),
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'userId' : IDL.Principal,
  'timestamp' : Time,
});
export const ScaryHubGameEntry = IDL.Record({
  'id' : IDL.Text,
  'lastPlayed' : IDL.Int,
  'theme' : IDL.Text,
  'title' : IDL.Text,
  'isScary' : IDL.Bool,
  'difficulty' : IDL.Text,
  'assets' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isFavorite' : IDL.Bool,
  'instructions' : IDL.Text,
  'highScore' : IDL.Nat,
  'category' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addVideoChannel' : IDL.Func([VideoChannel], [], []),
  'approveStoryProject' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStoryProject' : IDL.Func([IDL.Text], [], []),
  'deleteVideoChannel' : IDL.Func([IDL.Text], [], []),
  'getAllStoryProjects' : IDL.Func([], [IDL.Vec(StoryProject)], ['query']),
  'getCallerFavoriteChannels' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerStoryProjects' : IDL.Func([], [IDL.Vec(StoryProject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerVirtualPet' : IDL.Func([], [IDL.Opt(VirtualPetHub)], ['query']),
  'getRecentActivityEvents' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getScaryHubGames' : IDL.Func([], [IDL.Vec(ScaryHubGameEntry)], ['query']),
  'getStoryProject' : IDL.Func([IDL.Text], [IDL.Opt(StoryProject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoChannel' : IDL.Func([IDL.Text], [IDL.Opt(VideoChannel)], ['query']),
  'getVideoChannels' : IDL.Func([], [IDL.Vec(VideoChannel)], ['query']),
  'getVirtualPet' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VirtualPetHub)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markChannelAsFavorite' : IDL.Func([IDL.Text], [], []),
  'publishStoryProject' : IDL.Func([IDL.Text], [], []),
  'recordGamePlay' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCallerVirtualPet' : IDL.Func([VirtualPetHub], [], []),
  'saveStoryProject' : IDL.Func([StoryProject], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'unmarkChannelAsFavorite' : IDL.Func([IDL.Text], [], []),
  'updateGamesTrophies' : IDL.Func([], [IDL.Nat], []),
  'updateStoryProject' : IDL.Func([IDL.Text, StoryProject], [], []),
  'updateVideoChannel' : IDL.Func([IDL.Text, VideoChannel], [], []),
  'updateVideoChannelViews' : IDL.Func([IDL.Text], [], []),
  'welcomeBackReward' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const VideoChannel = IDL.Record({
    'categoryId' : IDL.Text,
    'lastPlayed' : IDL.Opt(Time),
    'channelId' : IDL.Text,
    'views' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'safe' : IDL.Bool,
    'lastUpdated' : IDL.Opt(Time),
    'description' : IDL.Text,
    'isFavorite' : IDL.Bool,
    'playlistUrl' : IDL.Text,
    'approved' : IDL.Bool,
    'totalVideos' : IDL.Nat,
    'iconUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TextBubble = IDL.Record({
    'content' : IDL.Text,
    'character' : IDL.Text,
    'style' : IDL.Text,
    'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
  });
  const AvatarConfig = IDL.Record({
    'body' : IDL.Text,
    'hair' : IDL.Text,
    'head' : IDL.Text,
    'headwear' : IDL.Text,
    'shoes' : IDL.Text,
    'pants' : IDL.Text,
  });
  const Character = IDL.Record({
    'name' : IDL.Text,
    'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
    'avatarConfig' : AvatarConfig,
  });
  const Prop = IDL.Record({
    'name' : IDL.Text,
    'type' : IDL.Text,
    'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
  });
  const Scene = IDL.Record({
    'background' : IDL.Text,
    'textBubbles' : IDL.Vec(TextBubble),
    'characters' : IDL.Vec(Character),
    'animations' : IDL.Vec(IDL.Text),
    'props' : IDL.Vec(Prop),
  });
  const StoryProject = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'scenes' : IDL.Vec(Scene),
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'approved' : IDL.Bool,
  });
  const AccessibilitySettings = IDL.Record({
    'highContrastMode' : IDL.Bool,
    'largeText' : IDL.Bool,
    'readAloudEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'mascotPreference' : IDL.Text,
    'theme' : IDL.Text,
    'approvedContacts' : IDL.Vec(IDL.Principal),
    'parentPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'screenTimeLimit' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'contentFilterLevel' : IDL.Text,
    'avatarConfig' : IDL.Opt(AvatarConfig),
    'accessibilitySettings' : AccessibilitySettings,
  });
  const VirtualPetHub = IDL.Record({
    'growthStage' : IDL.Nat,
    'accessories' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'warnedAboutExtremeChanges' : IDL.Bool,
    'happinessLevel' : IDL.Nat,
    'petName' : IDL.Text,
    'trophies' : IDL.Nat,
    'homeStyle' : IDL.Text,
    'decorations' : IDL.Vec(IDL.Text),
  });
  const ActivityType = IDL.Variant({
    'user_created' : IDL.Null,
    'game_played' : IDL.Record({ 'gameId' : IDL.Text, 'gameName' : IDL.Text }),
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'userId' : IDL.Principal,
    'timestamp' : Time,
  });
  const ScaryHubGameEntry = IDL.Record({
    'id' : IDL.Text,
    'lastPlayed' : IDL.Int,
    'theme' : IDL.Text,
    'title' : IDL.Text,
    'isScary' : IDL.Bool,
    'difficulty' : IDL.Text,
    'assets' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isFavorite' : IDL.Bool,
    'instructions' : IDL.Text,
    'highScore' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addVideoChannel' : IDL.Func([VideoChannel], [], []),
    'approveStoryProject' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStoryProject' : IDL.Func([IDL.Text], [], []),
    'deleteVideoChannel' : IDL.Func([IDL.Text], [], []),
    'getAllStoryProjects' : IDL.Func([], [IDL.Vec(StoryProject)], ['query']),
    'getCallerFavoriteChannels' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerStoryProjects' : IDL.Func([], [IDL.Vec(StoryProject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerVirtualPet' : IDL.Func([], [IDL.Opt(VirtualPetHub)], ['query']),
    'getRecentActivityEvents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getScaryHubGames' : IDL.Func([], [IDL.Vec(ScaryHubGameEntry)], ['query']),
    'getStoryProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StoryProject)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoChannel' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoChannel)],
        ['query'],
      ),
    'getVideoChannels' : IDL.Func([], [IDL.Vec(VideoChannel)], ['query']),
    'getVirtualPet' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VirtualPetHub)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markChannelAsFavorite' : IDL.Func([IDL.Text], [], []),
    'publishStoryProject' : IDL.Func([IDL.Text], [], []),
    'recordGamePlay' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCallerVirtualPet' : IDL.Func([VirtualPetHub], [], []),
    'saveStoryProject' : IDL.Func([StoryProject], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'unmarkChannelAsFavorite' : IDL.Func([IDL.Text], [], []),
    'updateGamesTrophies' : IDL.Func([], [IDL.Nat], []),
    'updateStoryProject' : IDL.Func([IDL.Text, StoryProject], [], []),
    'updateVideoChannel' : IDL.Func([IDL.Text, VideoChannel], [], []),
    'updateVideoChannelViews' : IDL.Func([IDL.Text], [], []),
    'welcomeBackReward' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };