/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessibilitySettings {
  'highContrastMode' : boolean,
  'largeText' : boolean,
  'readAloudEnabled' : boolean,
}
export interface ActivityEvent {
  'id' : bigint,
  'activityType' : ActivityType,
  'userId' : Principal,
  'timestamp' : Time,
}
export type ActivityType = { 'user_created' : null } |
  { 'game_played' : { 'gameId' : string, 'gameName' : string } };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AvatarConfig {
  'body' : string,
  'hair' : string,
  'head' : string,
  'headwear' : string,
  'shoes' : string,
  'pants' : string,
}
export interface Character {
  'name' : string,
  'position' : { 'x' : bigint, 'y' : bigint },
  'avatarConfig' : AvatarConfig,
}
export interface Prop {
  'name' : string,
  'type' : string,
  'position' : { 'x' : bigint, 'y' : bigint },
}
export interface ScaryHubGameEntry {
  'id' : string,
  'lastPlayed' : bigint,
  'theme' : string,
  'title' : string,
  'isScary' : boolean,
  'difficulty' : string,
  'assets' : Array<string>,
  'description' : string,
  'isFavorite' : boolean,
  'instructions' : string,
  'highScore' : bigint,
  'category' : string,
}
export interface Scene {
  'background' : string,
  'textBubbles' : Array<TextBubble>,
  'characters' : Array<Character>,
  'animations' : Array<string>,
  'props' : Array<Prop>,
}
export interface StoryProject {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'scenes' : Array<Scene>,
  'published' : boolean,
  'createdAt' : bigint,
  'approved' : boolean,
}
export interface TextBubble {
  'content' : string,
  'character' : string,
  'style' : string,
  'position' : { 'x' : bigint, 'y' : bigint },
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'age' : bigint,
  'mascotPreference' : string,
  'theme' : string,
  'approvedContacts' : Array<Principal>,
  'parentPrincipal' : Principal,
  'name' : string,
  'screenTimeLimit' : bigint,
  'avatarUrl' : string,
  'contentFilterLevel' : string,
  'avatarConfig' : [] | [AvatarConfig],
  'accessibilitySettings' : AccessibilitySettings,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoChannel {
  'categoryId' : string,
  'lastPlayed' : [] | [Time],
  'channelId' : string,
  'views' : bigint,
  'name' : string,
  'createdAt' : Time,
  'safe' : boolean,
  'lastUpdated' : [] | [Time],
  'description' : string,
  'isFavorite' : boolean,
  'playlistUrl' : string,
  'approved' : boolean,
  'totalVideos' : bigint,
  'iconUrl' : string,
}
export interface VirtualPetHub {
  'growthStage' : bigint,
  'accessories' : Array<string>,
  'userId' : Principal,
  'warnedAboutExtremeChanges' : boolean,
  'happinessLevel' : bigint,
  'petName' : string,
  'trophies' : bigint,
  'homeStyle' : string,
  'decorations' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addVideoChannel' : ActorMethod<[VideoChannel], undefined>,
  'approveStoryProject' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStoryProject' : ActorMethod<[string], undefined>,
  'deleteVideoChannel' : ActorMethod<[string], undefined>,
  'getAllStoryProjects' : ActorMethod<[], Array<StoryProject>>,
  'getCallerFavoriteChannels' : ActorMethod<[], Array<string>>,
  'getCallerStoryProjects' : ActorMethod<[], Array<StoryProject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerVirtualPet' : ActorMethod<[], [] | [VirtualPetHub]>,
  'getRecentActivityEvents' : ActorMethod<[bigint], Array<ActivityEvent>>,
  'getScaryHubGames' : ActorMethod<[], Array<ScaryHubGameEntry>>,
  'getStoryProject' : ActorMethod<[string], [] | [StoryProject]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoChannel' : ActorMethod<[string], [] | [VideoChannel]>,
  'getVideoChannels' : ActorMethod<[], Array<VideoChannel>>,
  'getVirtualPet' : ActorMethod<[Principal], [] | [VirtualPetHub]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markChannelAsFavorite' : ActorMethod<[string], undefined>,
  'publishStoryProject' : ActorMethod<[string], undefined>,
  'recordGamePlay' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCallerVirtualPet' : ActorMethod<[VirtualPetHub], undefined>,
  'saveStoryProject' : ActorMethod<[StoryProject], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unmarkChannelAsFavorite' : ActorMethod<[string], undefined>,
  'updateGamesTrophies' : ActorMethod<[], bigint>,
  'updateStoryProject' : ActorMethod<[string, StoryProject], undefined>,
  'updateVideoChannel' : ActorMethod<[string, VideoChannel], undefined>,
  'updateVideoChannelViews' : ActorMethod<[string], undefined>,
  'welcomeBackReward' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];