/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessibilitySettings {
  'highContrastMode' : boolean,
  'largeText' : boolean,
  'readAloudEnabled' : boolean,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AvatarConfig {
  'body' : string,
  'hair' : string,
  'head' : string,
  'headwear' : string,
  'shoes' : string,
  'pants' : string,
}
export interface Reward {
  'userId' : Principal,
  'badges' : Array<string>,
  'achievements' : Array<string>,
  'totalTrophies' : bigint,
  'virtualPetLevel' : bigint,
  'points' : bigint,
}
export interface SpinReward {
  'value' : string,
  'rewardType' : string,
  'timestamp' : bigint,
}
export interface SpinWheelResult {
  'remainingCooldown' : bigint,
  'pointsAdded' : bigint,
  'message' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'age' : bigint,
  'mascotPreference' : string,
  'theme' : string,
  'approvedContacts' : Array<Principal>,
  'parentPrincipal' : Principal,
  'name' : string,
  'screenTimeLimit' : bigint,
  'avatarUrl' : string,
  'contentFilterLevel' : string,
  'avatarConfig' : [] | [AvatarConfig],
  'accessibilitySettings' : AccessibilitySettings,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VirtualPetHub {
  'growthStage' : bigint,
  'accessories' : Array<string>,
  'userId' : Principal,
  'warnedAboutExtremeChanges' : boolean,
  'happinessLevel' : bigint,
  'petName' : string,
  'trophies' : bigint,
  'homeStyle' : string,
  'decorations' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimSpinReward' : ActorMethod<[bigint], SpinWheelResult>,
  'getCallerRewards' : ActorMethod<[], [] | [Reward]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastSpinTime' : ActorMethod<[], [] | [bigint]>,
  'getRemainingSpinCooldown' : ActorMethod<[], bigint>,
  'getSpinRewards' : ActorMethod<[], Array<SpinReward>>,
  'getTotalScore' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVirtualPetHub' : ActorMethod<[], [] | [VirtualPetHub]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordSpinReward' : ActorMethod<[SpinReward], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerRewards' : ActorMethod<[Reward], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveVirtualPetHub' : ActorMethod<[VirtualPetHub], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];