/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Reward = IDL.Record({
  'userId' : IDL.Principal,
  'badges' : IDL.Vec(IDL.Text),
  'achievements' : IDL.Vec(IDL.Text),
  'totalTrophies' : IDL.Nat,
  'virtualPetLevel' : IDL.Nat,
  'points' : IDL.Nat,
});
export const AvatarConfig = IDL.Record({
  'body' : IDL.Text,
  'hair' : IDL.Text,
  'head' : IDL.Text,
  'headwear' : IDL.Text,
  'shoes' : IDL.Text,
  'pants' : IDL.Text,
});
export const AccessibilitySettings = IDL.Record({
  'highContrastMode' : IDL.Bool,
  'largeText' : IDL.Bool,
  'readAloudEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'mascotPreference' : IDL.Text,
  'theme' : IDL.Text,
  'approvedContacts' : IDL.Vec(IDL.Principal),
  'parentPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'screenTimeLimit' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'contentFilterLevel' : IDL.Text,
  'avatarConfig' : IDL.Opt(AvatarConfig),
  'accessibilitySettings' : AccessibilitySettings,
});
export const SpinReward = IDL.Record({
  'value' : IDL.Text,
  'rewardType' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const VirtualPetHub = IDL.Record({
  'growthStage' : IDL.Nat,
  'accessories' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'warnedAboutExtremeChanges' : IDL.Bool,
  'happinessLevel' : IDL.Nat,
  'petName' : IDL.Text,
  'trophies' : IDL.Nat,
  'homeStyle' : IDL.Text,
  'decorations' : IDL.Vec(IDL.Text),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPointsFromSpin' : IDL.Func([IDL.Nat], [], []),
  'addTrophiesFromSpin' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerRewards' : IDL.Func([], [IDL.Opt(Reward)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastSpinTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getSpinRewards' : IDL.Func([], [IDL.Vec(SpinReward)], ['query']),
  'getTotalScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVirtualPetHub' : IDL.Func([], [IDL.Opt(VirtualPetHub)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'recordSpinReward' : IDL.Func([SpinReward], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerRewards' : IDL.Func([Reward], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVirtualPetHub' : IDL.Func([VirtualPetHub], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Reward = IDL.Record({
    'userId' : IDL.Principal,
    'badges' : IDL.Vec(IDL.Text),
    'achievements' : IDL.Vec(IDL.Text),
    'totalTrophies' : IDL.Nat,
    'virtualPetLevel' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const AvatarConfig = IDL.Record({
    'body' : IDL.Text,
    'hair' : IDL.Text,
    'head' : IDL.Text,
    'headwear' : IDL.Text,
    'shoes' : IDL.Text,
    'pants' : IDL.Text,
  });
  const AccessibilitySettings = IDL.Record({
    'highContrastMode' : IDL.Bool,
    'largeText' : IDL.Bool,
    'readAloudEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'mascotPreference' : IDL.Text,
    'theme' : IDL.Text,
    'approvedContacts' : IDL.Vec(IDL.Principal),
    'parentPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'screenTimeLimit' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'contentFilterLevel' : IDL.Text,
    'avatarConfig' : IDL.Opt(AvatarConfig),
    'accessibilitySettings' : AccessibilitySettings,
  });
  const SpinReward = IDL.Record({
    'value' : IDL.Text,
    'rewardType' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const VirtualPetHub = IDL.Record({
    'growthStage' : IDL.Nat,
    'accessories' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'warnedAboutExtremeChanges' : IDL.Bool,
    'happinessLevel' : IDL.Nat,
    'petName' : IDL.Text,
    'trophies' : IDL.Nat,
    'homeStyle' : IDL.Text,
    'decorations' : IDL.Vec(IDL.Text),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPointsFromSpin' : IDL.Func([IDL.Nat], [], []),
    'addTrophiesFromSpin' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerRewards' : IDL.Func([], [IDL.Opt(Reward)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastSpinTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getSpinRewards' : IDL.Func([], [IDL.Vec(SpinReward)], ['query']),
    'getTotalScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVirtualPetHub' : IDL.Func([], [IDL.Opt(VirtualPetHub)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'recordSpinReward' : IDL.Func([SpinReward], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerRewards' : IDL.Func([Reward], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVirtualPetHub' : IDL.Func([VirtualPetHub], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };