/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TextBubble {
    content: string;
    character: string;
    style: string;
    position: {
        x: bigint;
        y: bigint;
    };
}
export type Time = bigint;
export interface VirtualPetHub {
    growthStage: bigint;
    accessories: Array<string>;
    userId: Principal;
    warnedAboutExtremeChanges: boolean;
    happinessLevel: bigint;
    petName: string;
    trophies: bigint;
    homeStyle: string;
    decorations: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ScaryHubGameEntry {
    id: string;
    lastPlayed: bigint;
    theme: string;
    title: string;
    isScary: boolean;
    difficulty: string;
    assets: Array<string>;
    description: string;
    isFavorite: boolean;
    instructions: string;
    highScore: bigint;
    category: string;
}
export type ActivityType = {
    __kind__: "user_created";
    user_created: null;
} | {
    __kind__: "game_played";
    game_played: {
        gameId: string;
        gameName: string;
    };
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Character {
    name: string;
    position: {
        x: bigint;
        y: bigint;
    };
    avatarConfig: AvatarConfig;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Prop {
    name: string;
    type: string;
    position: {
        x: bigint;
        y: bigint;
    };
}
export interface ActivityEvent {
    id: bigint;
    activityType: ActivityType;
    userId: Principal;
    timestamp: Time;
}
export interface VideoChannel {
    categoryId: string;
    lastPlayed?: Time;
    channelId: string;
    views: bigint;
    name: string;
    createdAt: Time;
    safe: boolean;
    lastUpdated?: Time;
    description: string;
    isFavorite: boolean;
    playlistUrl: string;
    approved: boolean;
    totalVideos: bigint;
    iconUrl: string;
}
export interface AvatarConfig {
    body: string;
    hair: string;
    head: string;
    headwear: string;
    shoes: string;
    pants: string;
}
export interface AccessibilitySettings {
    highContrastMode: boolean;
    largeText: boolean;
    readAloudEnabled: boolean;
}
export interface StoryProject {
    id: string;
    title: string;
    owner: Principal;
    scenes: Array<Scene>;
    published: boolean;
    createdAt: bigint;
    approved: boolean;
}
export interface Scene {
    background: string;
    textBubbles: Array<TextBubble>;
    characters: Array<Character>;
    animations: Array<string>;
    props: Array<Prop>;
}
export interface UserProfile {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig?: AvatarConfig;
    accessibilitySettings: AccessibilitySettings;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addVideoChannel(channel: VideoChannel): Promise<void>;
    approveStoryProject(storyId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteStoryProject(storyId: string): Promise<void>;
    deleteVideoChannel(channelId: string): Promise<void>;
    getAllStoryProjects(): Promise<Array<StoryProject>>;
    getCallerFavoriteChannels(): Promise<Array<string>>;
    getCallerStoryProjects(): Promise<Array<StoryProject>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerVirtualPet(): Promise<VirtualPetHub | null>;
    getRecentActivityEvents(limit: bigint): Promise<Array<ActivityEvent>>;
    getScaryHubGames(): Promise<Array<ScaryHubGameEntry>>;
    getStoryProject(storyId: string): Promise<StoryProject | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoChannel(channelId: string): Promise<VideoChannel | null>;
    getVideoChannels(): Promise<Array<VideoChannel>>;
    getVirtualPet(user: Principal): Promise<VirtualPetHub | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markChannelAsFavorite(channelId: string): Promise<void>;
    publishStoryProject(storyId: string): Promise<void>;
    recordGamePlay(gameId: string, gameName: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCallerVirtualPet(pet: VirtualPetHub): Promise<void>;
    saveStoryProject(story: StoryProject): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    unmarkChannelAsFavorite(channelId: string): Promise<void>;
    updateGamesTrophies(): Promise<bigint>;
    updateStoryProject(storyId: string, updatedStory: StoryProject): Promise<void>;
    updateVideoChannel(channelId: string, updatedChannel: VideoChannel): Promise<void>;
    updateVideoChannelViews(channelId: string): Promise<void>;
    welcomeBackReward(): Promise<void>;
}
import type { AccessibilitySettings as _AccessibilitySettings, ActivityEvent as _ActivityEvent, ActivityType as _ActivityType, ApprovalStatus as _ApprovalStatus, AvatarConfig as _AvatarConfig, StoryProject as _StoryProject, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, VideoChannel as _VideoChannel, VirtualPetHub as _VirtualPetHub, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addVideoChannel(arg0: VideoChannel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoChannel(to_candid_VideoChannel_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoChannel(to_candid_VideoChannel_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveStoryProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveStoryProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveStoryProject(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteStoryProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStoryProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStoryProject(arg0);
            return result;
        }
    }
    async deleteVideoChannel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoChannel(arg0);
            return result;
        }
    }
    async getAllStoryProjects(): Promise<Array<StoryProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStoryProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStoryProjects();
            return result;
        }
    }
    async getCallerFavoriteChannels(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerFavoriteChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerFavoriteChannels();
            return result;
        }
    }
    async getCallerStoryProjects(): Promise<Array<StoryProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStoryProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStoryProjects();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerVirtualPet(): Promise<VirtualPetHub | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerVirtualPet();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerVirtualPet();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentActivityEvents(arg0: bigint): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivityEvents(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivityEvents(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScaryHubGames(): Promise<Array<ScaryHubGameEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScaryHubGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScaryHubGames();
            return result;
        }
    }
    async getStoryProject(arg0: string): Promise<StoryProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryProject(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryProject(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoChannel(arg0: string): Promise<VideoChannel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoChannel(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoChannel(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoChannels(): Promise<Array<VideoChannel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoChannels();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoChannels();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVirtualPet(arg0: Principal): Promise<VirtualPetHub | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVirtualPet(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVirtualPet(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async markChannelAsFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markChannelAsFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markChannelAsFavorite(arg0);
            return result;
        }
    }
    async publishStoryProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishStoryProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishStoryProject(arg0);
            return result;
        }
    }
    async recordGamePlay(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGamePlay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGamePlay(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerVirtualPet(arg0: VirtualPetHub): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerVirtualPet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerVirtualPet(arg0);
            return result;
        }
    }
    async saveStoryProject(arg0: StoryProject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStoryProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStoryProject(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unmarkChannelAsFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmarkChannelAsFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmarkChannelAsFavorite(arg0);
            return result;
        }
    }
    async updateGamesTrophies(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGamesTrophies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGamesTrophies();
            return result;
        }
    }
    async updateStoryProject(arg0: string, arg1: StoryProject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoryProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoryProject(arg0, arg1);
            return result;
        }
    }
    async updateVideoChannel(arg0: string, arg1: VideoChannel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoChannel(arg0, to_candid_VideoChannel_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoChannel(arg0, to_candid_VideoChannel_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVideoChannelViews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoChannelViews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoChannelViews(arg0);
            return result;
        }
    }
    async welcomeBackReward(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.welcomeBackReward();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.welcomeBackReward();
            return result;
        }
    }
}
function from_candid_ActivityEvent_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEvent): ActivityEvent {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_VideoChannel_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoChannel): VideoChannel {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvatarConfig]): AvatarConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VirtualPetHub]): VirtualPetHub | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoryProject]): StoryProject | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoChannel]): VideoChannel | null {
    return value.length === 0 ? null : from_candid_VideoChannel_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig: [] | [_AvatarConfig];
    accessibilitySettings: _AccessibilitySettings;
}): {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig?: AvatarConfig;
    accessibilitySettings: AccessibilitySettings;
} {
    return {
        age: value.age,
        mascotPreference: value.mascotPreference,
        theme: value.theme,
        approvedContacts: value.approvedContacts,
        parentPrincipal: value.parentPrincipal,
        name: value.name,
        screenTimeLimit: value.screenTimeLimit,
        avatarUrl: value.avatarUrl,
        contentFilterLevel: value.contentFilterLevel,
        avatarConfig: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.avatarConfig)),
        accessibilitySettings: value.accessibilitySettings
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityType: _ActivityType;
    userId: Principal;
    timestamp: _Time;
}): {
    id: bigint;
    activityType: ActivityType;
    userId: Principal;
    timestamp: Time;
} {
    return {
        id: value.id,
        activityType: from_candid_ActivityType_n22(_uploadFile, _downloadFile, value.activityType),
        userId: value.userId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: string;
    lastPlayed: [] | [_Time];
    channelId: string;
    views: bigint;
    name: string;
    createdAt: _Time;
    safe: boolean;
    lastUpdated: [] | [_Time];
    description: string;
    isFavorite: boolean;
    playlistUrl: string;
    approved: boolean;
    totalVideos: bigint;
    iconUrl: string;
}): {
    categoryId: string;
    lastPlayed?: Time;
    channelId: string;
    views: bigint;
    name: string;
    createdAt: Time;
    safe: boolean;
    lastUpdated?: Time;
    description: string;
    isFavorite: boolean;
    playlistUrl: string;
    approved: boolean;
    totalVideos: bigint;
    iconUrl: string;
} {
    return {
        categoryId: value.categoryId,
        lastPlayed: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastPlayed)),
        channelId: value.channelId,
        views: value.views,
        name: value.name,
        createdAt: value.createdAt,
        safe: value.safe,
        lastUpdated: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastUpdated)),
        description: value.description,
        isFavorite: value.isFavorite,
        playlistUrl: value.playlistUrl,
        approved: value.approved,
        totalVideos: value.totalVideos,
        iconUrl: value.iconUrl
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n33(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user_created: null;
} | {
    game_played: {
        gameId: string;
        gameName: string;
    };
}): {
    __kind__: "user_created";
    user_created: null;
} | {
    __kind__: "game_played";
    game_played: {
        gameId: string;
        gameName: string;
    };
} {
    return "user_created" in value ? {
        __kind__: "user_created",
        user_created: value.user_created
    } : "game_played" in value ? {
        __kind__: "game_played",
        game_played: value.game_played
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEvent>): Array<ActivityEvent> {
    return value.map((x)=>from_candid_ActivityEvent_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoChannel>): Array<VideoChannel> {
    return value.map((x)=>from_candid_VideoChannel_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n31(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_VideoChannel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoChannel): _VideoChannel {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig?: AvatarConfig;
    accessibilitySettings: AccessibilitySettings;
}): {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig: [] | [_AvatarConfig];
    accessibilitySettings: _AccessibilitySettings;
} {
    return {
        age: value.age,
        mascotPreference: value.mascotPreference,
        theme: value.theme,
        approvedContacts: value.approvedContacts,
        parentPrincipal: value.parentPrincipal,
        name: value.name,
        screenTimeLimit: value.screenTimeLimit,
        avatarUrl: value.avatarUrl,
        contentFilterLevel: value.contentFilterLevel,
        avatarConfig: value.avatarConfig ? candid_some(value.avatarConfig) : candid_none(),
        accessibilitySettings: value.accessibilitySettings
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: string;
    lastPlayed?: Time;
    channelId: string;
    views: bigint;
    name: string;
    createdAt: Time;
    safe: boolean;
    lastUpdated?: Time;
    description: string;
    isFavorite: boolean;
    playlistUrl: string;
    approved: boolean;
    totalVideos: bigint;
    iconUrl: string;
}): {
    categoryId: string;
    lastPlayed: [] | [_Time];
    channelId: string;
    views: bigint;
    name: string;
    createdAt: _Time;
    safe: boolean;
    lastUpdated: [] | [_Time];
    description: string;
    isFavorite: boolean;
    playlistUrl: string;
    approved: boolean;
    totalVideos: bigint;
    iconUrl: string;
} {
    return {
        categoryId: value.categoryId,
        lastPlayed: value.lastPlayed ? candid_some(value.lastPlayed) : candid_none(),
        channelId: value.channelId,
        views: value.views,
        name: value.name,
        createdAt: value.createdAt,
        safe: value.safe,
        lastUpdated: value.lastUpdated ? candid_some(value.lastUpdated) : candid_none(),
        description: value.description,
        isFavorite: value.isFavorite,
        playlistUrl: value.playlistUrl,
        approved: value.approved,
        totalVideos: value.totalVideos,
        iconUrl: value.iconUrl
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
